#
# Dockerfile.ubuntu-dev: General Ubuntu dev eenvironment w/ sudo rights
#
FROM ubuntu:20.04
MAINTAINER John Stultz <john.stultz@linaro.org>
ENV TERM xterm
# Update the image to the lastest updates
RUN apt-get update && apt-get -y dist-upgrade && apt-get clean && apt-get -y autoremove
# Get tools
RUN apt-get update && apt-get install -y \
	bc \
	cpio \
	gcc \
	git \
	kmod \
	libelf-dev \
	libncurses5-dev \
	libssl-dev \
	make \
	python \
	rsync \
	sudo \
	vim


# make username a variable, so the script is portable
# add '--build-arg user_name=$USER' to the docker build command
ARG --description="user name for container" user_name=docker

# Add $user_name user
RUN useradd -m $user_name && echo "$user_name:docker" | chpasswd && adduser $user_name sudo
USER $user_name


